//
//  CPU_MeterApp.swift
//  CPU_Meter
//
//  Overlay helper app showing CPU, GPU, and ANE load.
//  Generated by ChatGPT (GPT-5) for Jozef Belvončik – educational use.
//
//  © 2025 Jozef Belvončik MIT License
//

import SwiftUI
import AppKit

final class OverlayWindow: NSWindow {
    init(view: NSView) {
        // Increased default size for full text visibility
        super.init(contentRect: NSRect(x: 100, y: 100, width: 220, height: 140),
                   styleMask: [.borderless],
                   backing: .buffered,
                   defer: false)
        isOpaque = false
        backgroundColor = .clear
        level = .floating
        isMovableByWindowBackground = true
        collectionBehavior = [.canJoinAllSpaces]
        contentView = view
    }
    override var canBecomeKey: Bool { false }
}

@main
struct CPU_MeterApp: App {
    @NSApplicationDelegateAdaptor(AppDelegate.self) var appDelegate
    var body: some Scene { Settings { EmptyView() } }
}

final class AppDelegate: NSObject, NSApplicationDelegate {
    private var window: OverlayWindow?
    func applicationDidFinishLaunching(_ note: Notification) {
        let host = NSHostingView(rootView: OverlayView()
            .fixedSize(horizontal: false, vertical: false))
        window = OverlayWindow(view: host)
        window?.orderFrontRegardless()
        NSApp.setActivationPolicy(.accessory)
    }
}
