name: CPU_Meter
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    macOS: "13.0"

targets:
  CPU_Meter:
    type: application
    platform: macOS
    sources:
      - Sources
      - Resources
    settings:
      base:
        ARCHS: arm64
        ONLY_ACTIVE_ARCH: YES
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "-"
        PRODUCT_BUNDLE_IDENTIFIER: com.jbelvoncik.cpu-meter
    info:
      path: Info.plist
      properties:
        CFBundleName: CPU_Meter
        CFBundleExecutable: CPU_Meter
        CFBundleIdentifier: com.jbelvoncik.cpu-meter
        CFBundleVersion: "1.0"
        CFBundleShortVersionString: "1.0"
        LSUIElement: 1
        NSHighResolutionCapable: true
        CFBundleIconFile: AppIcon
