name: CPU_Meter
options:
  bundleIdPrefix: com.jbelvoncik
  createIntermediateGroups: true
targets:
  CPU_Meter:
    type: application
    platform: macOS
    sources:
      - Sources
      - Resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.jbelvoncik.cpu-meter
      CODE_SIGN_STYLE: Manual
      CODE_SIGN_IDENTITY: "-"
      DEVELOPMENT_TEAM: ""
    info:
      path: Info.plist
      properties:
        CFBundleName: CPU_Meter
        CFBundleExecutable: CPU_Meter
        CFBundleIdentifier: com.jbelvoncik.cpu-meter
        CFBundleVersion: "1.0"
        CFBundleShortVersionString: "1.0"
        LSUIElement: 1
        NSHighResolutionCapable: true
